server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    enabled: true
    user:
    password:
    baseline-description:
    baseline-version:

  devtools:
    add-properties: true

