server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    baseline-description: "init"
    baseline-version: 0
  mail:
    host: smtp.gmail.com
    port: 587
    username: apolar1453@gmail.com
    password: rchipqjztneykzit
    properties:
      mail:
        smtp:
          auth:true
        starttls:
          enable: true
          required: true





